# Site settings
title: ZStack
email: info@zstack.org

name: "zstack"
description: "ZStack is open source IaaS software managing resources of compute, storage, networking throughout a datacenter all by APIs."

#contacts
twitter_username: "zstack_org"

baseurl: ""
url: "http://zstack.org"


# Build settings
markdown: rdiscount
permalink: none
highlighter: pygments
relative_permalinks: false
