# Site settings
title: ZStack
email: info@zstack.org

name: "zstack"
description: "ZStack is open source IaaS software managing resources of compute, storage, networking throughout a datacenter all by APIs."

#contacts
twitter_username: "zstack_org"

baseurl: ""
url: "http://zstack.org"


# Build settings
markdown: rdiscount
permalink: none
highlighter: pygments
relative_permalinks: false

# multiple languages plugins.
gems:           ['jekyll-multiple-languages']

languages:          ['en', 'cn']
#
language_default:   'en'
#
fill_default_content: true

install_script_en: "http://download.zstack.org/releases/0.9/0.9.0/zstack-install.sh"
vr_en: "http://download.zstack.org/templates/zstack-virtualrouter-1.1.0.qcow2"
all_in_one_en: "http://download.zstack.org/releases/1.3/1.3.0/zstack-installer-1.3.0.bin"
war_en: "http://download.zstack.org/releases/1.3/1.3.0/zstack.war"
tgz: "zstack-installer-1.3.0.bin"

install_script_ch: "http://7xi3lj.com1.z0.glb.clouddn.com/releases/1.1/1.1.0/zstack-install.sh"
vr_ch: "http://download.zstack.org/templates/zstack-virtualrouter-1.1.0.qcow2"
all_in_one_ch: "http://download.zstack.org/releases/1.3/1.3.0/zstack-installer-1.3.0.bin"
#all_in_one_ch: "http://7xi3lj.com1.z0.glb.clouddn.com/releases/1.0/1.0.1/zstack-installer-1.0.1.bin"
#war_ch: "http://7xi3lj.com1.z0.glb.clouddn.com/releases/1.0/1.0.1/zstack.war"
war_ch: "http://download.zstack.org/releases/1.3/1.3.0/zstack.war"
all_in_one_md5: "b9cf433d8fa1a572bd8139a929d4281c"

zstack_image: "http://download.zstack.org/templates/zstack-image-1.2.qcow2"
zstack_image_md5: "a19e9804ac514579cdde9869e91378d4"

zstack_centos7_iso: "http://download.zstack.org/ISO/ZStack-Community-x86_64-DVD-1.3.0.iso"
zstack_centos7_md5: "80a87506325702d7f3d453a54041ddcb"

zstack_centos7_iso_baidu: "http://pan.baidu.com/s/1hsqCEfa"
