# Site settings
title: ZStack
email: info@zstack.org

name: "zstack"
description: "An open source, scalable, easy IaaS software"

#contacts
twitter_username: "zstack_org"

baseurl: ""
url: "http://zstack.org"


# Build settings
markdown: rdiscount
permalink: none
highlighter: pygments
relative_permalinks: false
