# Site settings
title: ZStack
email: info@zstack.org

name: "zstack"
description: "ZStack is open source IaaS software managing resources of compute, storage, networking throughout a datacenter all by APIs."

#contacts
twitter_username: "zstack_org"

baseurl: ""
url: "http://zstack.org"


# Build settings
markdown: rdiscount
permalink: none
highlighter: pygments
relative_permalinks: false

# multiple languages plugins.
gems:           ['jekyll-multiple-languages']

languages:          ['en', 'cn']
#
language_default:   'en'
#
fill_default_content: true

install_script_en: "http://download.zstack.org/releases/0.9/0.9.0/zstack-install.sh"
vr_en: "http://download.zstack.org/releases/0.9/0.9.0/zstack-virtualrouter-0.9.0.qcow2"
all_in_one_en: "http://download.zstack.org/releases/1.0/1.0.3/0313/zstack-installer-1.0.3-0313.bin"
war_en: "http://download.zstack.org/releases/1.0/1.0.3/0313/zstack.war"
tgz: "zstack-installer-1.0.3.bin"

install_script_ch: "http://7xi3lj.com1.z0.glb.clouddn.com/releases/1.0/1.0.0/zstack-install.sh"
vr_ch: "http://7xi3lj.com1.z0.glb.clouddn.com/releases/0.9/0.9.0/zstack-virtualrouter-0.9.0.qcow2"
all_in_one_ch: "http://download.zstack.org/releases/1.0/1.0.3/0313/zstack-installer-1.0.3-0313.bin"
#all_in_one_ch: "http://7xi3lj.com1.z0.glb.clouddn.com/releases/1.0/1.0.1/zstack-installer-1.0.1.bin"
#war_ch: "http://7xi3lj.com1.z0.glb.clouddn.com/releases/1.0/1.0.1/zstack.war"
war_ch: "http://download.zstack.org/releases/1.0/1.0.3/0313/zstack.war"
all_in_one_md5: "0cf02498efe9f034275443b40334d3b9"

zstack_image: "http://download.zstack.org/templates/zstack-image-0.0.7.qcow2"
zstack_image_md5: "6bdfb1fa6d21f650497448126e180b23"

